app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(navPage = "demoTab",wait_=FALSE, values_=FALSE)
app$setInputs(demoDataset = "Exp1_R25_prot",wait_=FALSE, values_=FALSE)
app$setInputs(loadDemoDataset = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Filtering-rstBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Filtering-prevBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Filtering-nextBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Normalization-rstBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Normalization-prevBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_Normalization-nextBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_ProtImputation-rstBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_ProtImputation-prevBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_ProtImputation-nextBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_HypothesisTest-rstBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_HypothesisTest-prevBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_HypothesisTest-nextBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(DS_tabSetPanel = "DS_tabGeneral",wait_=FALSE, values_=FALSE)
app$setInputs(showDataLabels = FALSE,wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_GO-rstBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_GO-prevBtn` = "click",wait_=FALSE, values_=FALSE)
app$setInputs(`moduleProcess_GO-nextBtn` = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(navPage = "DescriptiveStatisticsTab",wait_=FALSE, values_=FALSE)
app$setInputs(`overview_DS-StaticDataTable_rows_current` = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`overview_DS-StaticDataTable_rows_all` = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`overview_DS-StaticDataTable_state` = c(1701919059912, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(DS_tabSetPanel = "DS_DataExplorer",wait_=FALSE, values_=FALSE)
app$setInputs(`test-DS_TabsChoice` = "tabpData",wait_=FALSE, values_=FALSE)
app$setInputs(`test-viewpData_rows_current` = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`test-viewpData_rows_all` = c(1, 2, 3, 4, 5, 6), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$setInputs(`test-viewpData_state` = c(1701919064595, 0, 126, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), 0, 0, 0, 0), allowInputNoBinding_ = TRUE,wait_=FALSE, values_=FALSE)
app$snapshot()
